# tickers:
#   - 'CELH'
#   - 'AAPL'
#   - 'TSLA'
#   - 'MSFT'
#   - 'GOOGL'
#   - 'SPY'
#   - 'TMDX'
#   - 'ASPN'
#   - 'MSTR'
#   - 'COIN'
#   - 'YANG'
#   - 'TLT'
#   - 'OKLO'
#   - 'CELH'
#   - 'APP'
#   - 'FOUR'
#   - 'NU'
#   - 'UBER'
#   - 'DKNG'
#   - 'SQ'
#   - 'CPNG'
#   - 'MELI'
#   - 'ONON'
#   - 'TDW'
#   - 'TTD'
#   - 'HOOD'
#   - 'SPY'
#   - 'MU'
#   - 'AMD'
#   - 'VRT'
#   - 'ZETA'
#   - 'RDDT'
#   - 'SE'
#   - 'COIN'
#   - 'DELL'
#   - 'GUSH'
#   - 'HROW'
#   - 'S'
#   - 'HIMS'
#   - 'EXAS'
#   - 'CLBT'
#   - 'AFRM'
#   - 'SG'
#   - 'LNTH'
#   - 'BA'
#   - 'ELF'
#   - 'NTNX'
#   - 'MDB'
#   - 'DECK'
#   - 'SNAP'
#   - 'CCJ'
#   - 'BLDR'
#   - 'PRCT'
#   - 'SN'
#   - 'SPOT'
#   - 'CLPT'
#   - 'INMD'
#   - 'COST'
#   - 'MNDY'
#   - 'FICO'
#   - 'ROKU'
#   - 'SBUX'
#   - 'ISRG'
#   - 'WING'
#   - 'IOT'
#   - 'FRPT'
#   - 'BROS'
#   - 'AXON'
#   - 'CAVA'
#   - 'PLTR'
#   - 'RBLX'
#   - 'IWM'
#   - 'GDXU'
#   - 'AVGO'
#   - 'DXYZ'
#   - 'META'
#   - 'UPWK'
#   - 'UPST'
#   - 'U'
#   - 'UVIX'
#   - 'SVIX'
#   - 'DXYZ'
#   - 'DJT'
#   - 'LUNR'
#   - 'DAL'
#   - 'AAL'
#   - 'IONQ'
#   - 'ETSY'
#   - 'LULU'
#   - 'RBLX'
#   - 'LLY'
#   - 'BABA'
#   - 'FUTU'
#   - 'BIDU'
#   - 'AEHR'
#   - 'NFLX'
#   - 'RBLX'
#   - 'NKE'
#   - 'SYM'
#   - 'APLD'
#   - 'PDD'
#   - 'SOXS'
#   - 'USD'
#   - 'SOXL'
#   - 'VST'
#   - 'CEG'
#   - 'SMR'
#   - 'NNE'
#   - 'RIVN'

tickers:
  - AAPL
  - MSFT
  - GOOGL
  - CELH