numerical_features:
  - GTY1
  - 趋势线
  - 警戒线
  - XIAO1
  - XIAO2
  - XIAO3
  - XIAO4
  - XIAO5
  - 主力出没
  - 洗盘
  - AI红柱
  - AI绿柱
  - DIFF
  - DEA
  - MACD
  - VAR1
  - VAR2
  - VAR3
  - VAR4
  - VAR5
  - VAR6
  - VAR7
  - VAR8
  - VAR9
  - VARA
  - VARB
  - VARC
  - VARD
  - VARE
  - VARF
  - 火焰山底
  - AA
  - RSI
  - FF
  - MA15
  - 爆量
  - RSV
  - K
  - D
  - J
  - V11
  - 能量
  - 平滑能量
  - 能量惯性
  - JJZ
  - QJ0Z
  - 买1
  - 买2
  - 卖1
  - 卖2
  - DTZ
  - 主力持仓
  - JJ
  - QJ0
  - TD1
  - DD1
  - DD2
  - TD2
  - TD
  - DA
  - XD1
  - XD2
  - TZ
  - DT
  - 散户持仓
  - RSI1
  - AR
  - 资金进出趋势
  - 散户
  - VAR10
  - VAR11
  - VAR12
  - VAR13
  - VAR14
  - VAR15
  - VAR16
  - XX
  - YY
  - 短线看红涨绿跌
  - 买线
  - 卖线
  - VAR18
  - VAR19
  - 柱1
  - 柱2
  - VA
  - OBV1
  - OBV2
  - OBV3
  - MAC3
  - 红箭头_count_last_5d
  - 红箭头_count_last_15d
  - 红箭头_count_last_30d
  - 红箭头_count_last_90d
  - 红箭头_last_price_5d
  - 红箭头_last_price_15d
  - 红箭头_last_price_30d
  - 红箭头_last_price_90d
  - 绿箭头_count_last_5d
  - 绿箭头_count_last_15d
  - 绿箭头_count_last_30d
  - 绿箭头_count_last_90d
  - 绿箭头_last_price_5d
  - 绿箭头_last_price_15d
  - 绿箭头_last_price_30d
  - 绿箭头_last_price_90d
  - BU_count_last_5d
  - BU_count_last_15d
  - BU_count_last_30d
  - BU_count_last_90d
  - BU_last_price_5d
  - BU_last_price_15d
  - BU_last_price_30d
  - BU_last_price_90d
  - SEL_count_last_5d
  - SEL_count_last_15d
  - SEL_count_last_30d
  - SEL_count_last_90d
  - SEL_last_price_5d
  - SEL_last_price_15d
  - SEL_last_price_30d
  - SEL_last_price_90d
  - 启动上涨_count_last_5d
  - 启动上涨_count_last_15d
  - 启动上涨_count_last_30d
  - 启动上涨_count_last_90d
  - 启动上涨_last_price_5d
  - 启动上涨_last_price_15d
  - 启动上涨_last_price_30d
  - 启动上涨_last_price_90d
  - AI红柱_count_last_5d
  - AI红柱_count_last_15d
  - AI红柱_count_last_30d
  - AI红柱_count_last_90d
  - AI红柱_last_price_5d
  - AI红柱_last_price_15d
  - AI红柱_last_price_30d
  - AI红柱_last_price_90d
  - AI绿柱_count_last_5d
  - AI绿柱_count_last_15d
  - AI绿柱_count_last_30d
  - AI绿柱_count_last_90d
  - AI绿柱_last_price_5d
  - AI绿柱_last_price_15d
  - AI绿柱_last_price_30d
  - AI绿柱_last_price_90d
  - brown_底背离_count_last_5d
  - brown_底背离_count_last_15d
  - brown_底背离_count_last_30d
  - brown_底背离_count_last_90d
  - brown_底背离_last_price_5d
  - brown_底背离_last_price_15d
  - brown_底背离_last_price_30d
  - brown_底背离_last_price_90d
  - white_底背离_count_last_5d
  - white_底背离_count_last_15d
  - white_底背离_count_last_30d
  - white_底背离_count_last_90d
  - white_底背离_last_price_5d
  - white_底背离_last_price_15d
  - white_底背离_last_price_30d
  - white_底背离_last_price_90d
  - green_顶背离_count_last_5d
  - green_顶背离_count_last_15d
  - green_顶背离_count_last_30d
  - green_顶背离_count_last_90d
  - green_顶背离_last_price_5d
  - green_顶背离_last_price_15d
  - green_顶背离_last_price_30d
  - green_顶背离_last_price_90d
  - 火焰山底_count_last_5d
  - 火焰山底_count_last_15d
  - 火焰山底_count_last_30d
  - 火焰山底_count_last_90d
  - 火焰山底_last_price_5d
  - 火焰山底_last_price_15d
  - 火焰山底_last_price_30d
  - 火焰山底_last_price_90d
  - 探底点_count_last_5d
  - 探底点_count_last_15d
  - 探底点_count_last_30d
  - 探底点_count_last_90d
  - 探底点_last_price_5d
  - 探底点_last_price_15d
  - 探底点_last_price_30d
  - 探底点_last_price_90d
  - 爆量寻牛点_count_last_5d
  - 爆量寻牛点_count_last_15d
  - 爆量寻牛点_count_last_30d
  - 爆量寻牛点_count_last_90d
  - 爆量寻牛点_last_price_5d
  - 爆量寻牛点_last_price_15d
  - 爆量寻牛点_last_price_30d
  - 爆量寻牛点_last_price_90d
  - 能量买卖信号_count_last_5d
  - 能量买卖信号_count_last_15d
  - 能量买卖信号_count_last_30d
  - 能量买卖信号_count_last_90d
  - 能量买卖信号_last_price_5d
  - 能量买卖信号_last_price_15d
  - 能量买卖信号_last_price_30d
  - 能量买卖信号_last_price_90d
  - 黄钻_count_last_5d
  - 黄钻_count_last_15d
  - 黄钻_count_last_30d
  - 黄钻_count_last_90d
  - 黄钻_last_price_5d
  - 黄钻_last_price_15d
  - 黄钻_last_price_30d
  - 黄钻_last_price_90d
  - 绿钻_count_last_5d
  - 绿钻_count_last_15d
  - 绿钻_count_last_30d
  - 绿钻_count_last_90d
  - 绿钻_last_price_5d
  - 绿钻_last_price_15d
  - 绿钻_last_price_30d
  - 绿钻_last_price_90d
  - 大底_count_last_5d
  - 大底_count_last_15d
  - 大底_count_last_30d
  - 大底_count_last_90d
  - 大底_last_price_5d
  - 大底_last_price_15d
  - 大底_last_price_30d
  - 大底_last_price_90d
  - 冲刺红柱
  - 下降白柱
  - 天线
  - brown_底背离
  - white_底背离
  - green_顶背离
  - 弱
  - 强弱分界
  
categorical_features:

  - 底背离
  - 顶背离

  - XG
  - XGA
  - XG1
  - 探底点
  - 爆量寻牛点
  - 能量买卖信号

  - 黄钻
  - 绿钻
  - 大底
  - 博弈
  - 底部扶摇直上
  - XG
  - 黄柱
  - 逃顶
  - 是底
  - 趋势多
  - 趋势空
  - BU
  - SEL
  - 启动上涨

  - 红箭头
  - 绿箭头